# Generated by Django 5.2.4 on 2025-08-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_codesnippet_codeissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
